Develop
MaximProkopen/Hillel_DZ pull request #1
Opened 2022-02-07 19:57 UTC by MaximProkopen

2022-02-07 20:03 UTC, fo0lman requested changes
все типовые замечания делать отдельными комитами

2022-02-07 20:03 UTC, fo0lman commented on DZ3/pages/search.html
> +        </div>
Это беда, тем более в таблице. а как же забыл за валидатор?

2022-02-07 20:03 UTC, fo0lman commented on index.html
>          <form action="DZ2/index.html">
ещё можно в этом pr удалить index.html который у тебя в ветке main

2022-02-07 20:19 UTC, MaximProkopen commented on DZ3/pages/search.html
> +        </div>
Не ту версию вставил

2022-02-07 21:32 UTC, fo0lman requested changes
Не все запрошеные изменения

2022-02-08 17:21 UTC, fo0lman approved these changes
Всё ок! Теперь 
* main 
git fetch
git pull

2022-02-08 17:21 UTC, merged